"""
Seed data for onboarding assessments and lesson content across languages.

This module centralizes vocabulary translations and assessment questions so we
can consistently generate lessons for multiple languages (Spanish, French,
German, Korean, etc.). It is intentionally framework-agnostic: no direct
references to Django models so it can be safely reused by migrations,
management commands, or future scripts.
"""

from __future__ import annotations

from typing import Dict, List

from home.language_registry import DEFAULT_LANGUAGE

LESSON_CARD_DATA: Dict[str, Dict] = {
    'shapes': {
        'title_template': 'Shapes in {language}',
        'description_template': 'Learn essential shape names in {language}',
        'slug': 'shapes',
        'order': 1,
        'category': 'Shapes',
        'quiz_count': 5,
        'xp_value': 100,
        'cards': [
            {
                'front': 'Circle',
                'translations': {
                    'Spanish': 'Círculo',
                    'French': 'Cercle',
                    'German': 'Kreis',
                    'Korean': '원 (won)',
                    'Italian': 'Cerchio',
                    'Japanese': '円 (en)',
                    'Chinese': '圆形',
                    'Portuguese': 'Círculo',
                    'Russian': 'Круг',
                    'Arabic': 'دائرة',
                },
            },
            {
                'front': 'Square',
                'translations': {
                    'Spanish': 'Cuadrado',
                    'French': 'Carré',
                    'German': 'Quadrat',
                    'Korean': '정사각형 (jeong-sagak-hyeong)',
                    'Italian': 'Quadrato',
                    'Japanese': '正方形 (seihōkei)',
                    'Chinese': '正方形',
                    'Portuguese': 'Quadrado',
                    'Russian': 'Квадрат',
                    'Arabic': 'مربع',
                },
            },
            {
                'front': 'Triangle',
                'translations': {
                    'Spanish': 'Triángulo',
                    'French': 'Triangle',
                    'German': 'Dreieck',
                    'Korean': '삼각형 (sam-gak-hyeong)',
                    'Italian': 'Triangolo',
                    'Japanese': '三角形 (sankakkei)',
                    'Chinese': '三角形',
                    'Portuguese': 'Triângulo',
                    'Russian': 'Треугольник',
                    'Arabic': 'مثلث',
                },
            },
            {
                'front': 'Rectangle',
                'translations': {
                    'Spanish': 'Rectángulo',
                    'French': 'Rectangle',
                    'German': 'Rechteck',
                    'Korean': '직사각형 (jik-sagak-hyeong)',
                    'Italian': 'Rettangolo',
                    'Japanese': '長方形 (chōhōkei)',
                    'Chinese': '长方形',
                    'Portuguese': 'Retângulo',
                    'Russian': 'Прямоугольник',
                    'Arabic': 'مستطيل',
                },
            },
            {
                'front': 'Oval',
                'translations': {
                    'Spanish': 'Óvalo',
                    'French': 'Ovale',
                    'German': 'Oval',
                    'Korean': '타원형 (ta-won-hyeong)',
                    'Italian': 'Ovale',
                    'Japanese': '楕円 (daen)',
                    'Chinese': '椭圆形',
                    'Portuguese': 'Oval',
                    'Russian': 'Овал',
                    'Arabic': 'بيضاوي',
                },
            },
            {
                'front': 'Star',
                'translations': {
                    'Spanish': 'Estrella',
                    'French': 'Étoile',
                    'German': 'Stern',
                    'Korean': '별 (byeol)',
                    'Italian': 'Stella',
                    'Japanese': '星 (hoshi)',
                    'Chinese': '星形',
                    'Portuguese': 'Estrela',
                    'Russian': 'Звезда',
                    'Arabic': 'نجمة',
                },
            },
            {
                'front': 'Heart',
                'translations': {
                    'Spanish': 'Corazón',
                    'French': 'Cœur',
                    'German': 'Herz',
                    'Korean': '하트 (hateu)',
                    'Italian': 'Cuore',
                    'Japanese': 'ハート (hāto)',
                    'Chinese': '心形',
                    'Portuguese': 'Coração',
                    'Russian': 'Сердце',
                    'Arabic': 'قلب',
                },
            },
            {
                'front': 'Diamond',
                'translations': {
                    'Spanish': 'Diamante',
                    'French': 'Losange',
                    'German': 'Raute',
                    'Korean': '마름모 (mareum-mo)',
                    'Italian': 'Rombo',
                    'Japanese': 'ひし形 (hishigata)',
                    'Chinese': '菱形',
                    'Portuguese': 'Losango',
                    'Russian': 'Ромб',
                    'Arabic': 'معين',
                },
            },
        ],
    },
    'colors': {
        'title_template': 'Colors in {language}',
        'description_template': 'Learn everyday colors in {language}',
        'slug': 'colors',
        'order': 2,
        'category': 'Colors',
        'quiz_count': 8,
        'xp_value': 120,
        'cards': [
            {
                'front': 'Red',
                'translations': {
                    'Spanish': 'Rojo',
                    'French': 'Rouge',
                    'German': 'Rot',
                    'Korean': '빨간색 (ppalgan-saek)',
                    'Italian': 'Rosso',
                    'Japanese': '赤 (aka)',
                    'Chinese': '红色',
                    'Portuguese': 'Vermelho',
                    'Russian': 'Красный',
                    'Arabic': 'أحمر',
                },
            },
            {
                'front': 'Blue',
                'translations': {
                    'Spanish': 'Azul',
                    'French': 'Bleu',
                    'German': 'Blau',
                    'Korean': '파란색 (paran-saek)',
                    'Italian': 'Blu',
                    'Japanese': '青 (ao)',
                    'Chinese': '蓝色',
                    'Portuguese': 'Azul',
                    'Russian': 'Синий',
                    'Arabic': 'أزرق',
                },
            },
            {
                'front': 'Yellow',
                'translations': {
                    'Spanish': 'Amarillo',
                    'French': 'Jaune',
                    'German': 'Gelb',
                    'Korean': '노란색 (noran-saek)',
                    'Italian': 'Giallo',
                    'Japanese': '黄色 (kiiro)',
                    'Chinese': '黄色',
                    'Portuguese': 'Amarelo',
                    'Russian': 'Жёлтый',
                    'Arabic': 'أصفر',
                },
            },
            {
                'front': 'Green',
                'translations': {
                    'Spanish': 'Verde',
                    'French': 'Vert',
                    'German': 'Grün',
                    'Korean': '초록색 (chorok-saek)',
                    'Italian': 'Verde',
                    'Japanese': '緑 (midori)',
                    'Chinese': '绿色',
                    'Portuguese': 'Verde',
                    'Russian': 'Зелёный',
                    'Arabic': 'أخضر',
                },
            },
            {
                'front': 'Purple',
                'translations': {
                    'Spanish': 'Morado',
                    'French': 'Violet',
                    'German': 'Lila',
                    'Korean': '보라색 (bora-saek)',
                    'Italian': 'Viola',
                    'Japanese': '紫 (murasaki)',
                    'Chinese': '紫色',
                    'Portuguese': 'Roxo',
                    'Russian': 'Фиолетовый',
                    'Arabic': 'بنفسجي',
                },
            },
            {
                'front': 'Orange',
                'translations': {
                    'Spanish': 'Naranja',
                    'French': 'Orange',
                    'German': 'Orange',
                    'Korean': '주황색 (juhwang-saek)',
                    'Italian': 'Arancione',
                    'Japanese': 'オレンジ (orenji)',
                    'Chinese': '橙色',
                    'Portuguese': 'Laranja',
                    'Russian': 'Оранжевый',
                    'Arabic': 'برتقالي',
                },
            },
            {
                'front': 'Pink',
                'translations': {
                    'Spanish': 'Rosa',
                    'French': 'Rose',
                    'German': 'Rosa',
                    'Korean': '분홍색 (bunhong-saek)',
                    'Italian': 'Rosa',
                    'Japanese': 'ピンク (pinku)',
                    'Chinese': '粉色',
                    'Portuguese': 'Rosa',
                    'Russian': 'Розовый',
                    'Arabic': 'وردي',
                },
            },
            {
                'front': 'Brown',
                'translations': {
                    'Spanish': 'Marrón',
                    'French': 'Marron',
                    'German': 'Braun',
                    'Korean': '갈색 (galsaek)',
                    'Italian': 'Marrone',
                    'Japanese': '茶色 (chairo)',
                    'Chinese': '棕色',
                    'Portuguese': 'Marrom',
                    'Russian': 'Коричневый',
                    'Arabic': 'بني',
                },
            },
            {
                'front': 'Black',
                'translations': {
                    'Spanish': 'Negro',
                    'French': 'Noir',
                    'German': 'Schwarz',
                    'Korean': '검은색 (geomeun-saek)',
                    'Italian': 'Nero',
                    'Japanese': '黒 (kuro)',
                    'Chinese': '黑色',
                    'Portuguese': 'Preto',
                    'Russian': 'Чёрный',
                    'Arabic': 'أسود',
                },
            },
            {
                'front': 'White',
                'translations': {
                    'Spanish': 'Blanco',
                    'French': 'Blanc',
                    'German': 'Weiß',
                    'Korean': '하얀색 (hayan-saek)',
                    'Italian': 'Bianco',
                    'Japanese': '白 (shiro)',
                    'Chinese': '白色',
                    'Portuguese': 'Branco',
                    'Russian': 'Белый',
                    'Arabic': 'أبيض',
                },
            },
        ],
    },
}


ONBOARDING_QUESTION_SETS: Dict[str, List[Dict]] = {
    'French': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "What is the French word for 'hello'?",
            'option_a': 'Salut',
            'option_b': 'Bonjour',
            'option_c': 'Merci',
            'option_d': 'Au revoir',
            'correct_answer': 'B',
            'explanation': "'Bonjour' is the standard greeting meaning 'hello' or 'good day'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in French?",
            'option_a': 'Pardon',
            'option_b': 'Merci',
            'option_c': 'S’il vous plaît',
            'option_d': 'Bonsoir',
            'correct_answer': 'B',
            'explanation': "'Merci' translates directly to 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which phrase means 'I am'?",
            'option_a': 'Je suis',
            'option_b': 'Tu es',
            'option_c': 'Il est',
            'option_d': 'Nous sommes',
            'correct_answer': 'A',
            'explanation': "'Je suis' is the first person singular form of 'être' (to be).",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in French?",
            'option_a': 'Livre',
            'option_b': 'Rouge',
            'option_c': 'Table',
            'option_d': 'Chaise',
            'correct_answer': 'B',
            'explanation': "'Rouge' means 'red'. The other words mean book, table, and chair.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "How do you say 'I ate' in French?",
            'option_a': 'Je mange',
            'option_b': "J'ai mangé",
            'option_c': 'Je mangerai',
            'option_d': 'Je mangeais',
            'correct_answer': 'B',
            'explanation': "“J'ai mangé” is the passé composé (simple past) form meaning 'I ate'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete the sentence: 'Hier, je ___ au parc.' (Yesterday I went to the park.)",
            'option_a': 'vais',
            'option_b': 'suis allé',
            'option_c': 'irai',
            'option_d': 'allais',
            'correct_answer': 'B',
            'explanation': "'Je suis allé' is the correct past form with the auxiliary 'être' for aller.",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does 'Il fait beau' mean?",
            'option_a': "It's raining",
            'option_b': 'The weather is nice',
            'option_c': "It's very cold",
            'option_d': "It's windy",
            'correct_answer': 'B',
            'explanation': "'Il fait beau' describes pleasant weather.",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Choose the correct comparative: 'Ma sœur est ___ que moi.' (My sister is taller than me.)",
            'option_a': 'plus grande',
            'option_b': 'plus grand',
            'option_c': 'aussi grande',
            'option_d': 'très grande',
            'correct_answer': 'A',
            'explanation': "Comparatives use 'plus + adjective + que'; 'grande' agrees with 'sœur'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Complete with the subjunctive: 'Il faut que tu ___ tôt.' (You must come early.)",
            'option_a': 'viens',
            'option_b': 'venir',
            'option_c': 'viennes',
            'option_d': 'viendras',
            'correct_answer': 'C',
            'explanation': "'Il faut que' triggers the subjunctive: 'tu viennes'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Which sentence correctly uses a conditional structure?",
            'option_a': "Si je travaille, je dormais.",
            'option_b': "Si j'avais le temps, je voyagerais.",
            'option_c': 'Je voyagerai si j’avais le temps.',
            'option_d': "Si j'ai le temps, je voyagerais.",
            'correct_answer': 'B',
            'explanation': "A proper conditional pairs 'si' + imperfect with conditional: 'je voyagerais'.",
            'difficulty_points': 3,
        },
    ],
    'Italian': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "What is the Italian word for 'hello'?",
            'option_a': 'Arrivederci',
            'option_b': 'Ciao',
            'option_c': 'Grazie',
            'option_d': 'Per favore',
            'correct_answer': 'B',
            'explanation': "'Ciao' is the common informal greeting meaning 'hello'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in Italian?",
            'option_a': 'Prego',
            'option_b': 'Mi dispiace',
            'option_c': 'Grazie',
            'option_d': 'Scusa',
            'correct_answer': 'C',
            'explanation': "'Grazie' is used to say 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which phrase means 'I am'?",
            'option_a': 'Io sono',
            'option_b': 'Tu sei',
            'option_c': 'Lui è',
            'option_d': 'Noi siamo',
            'correct_answer': 'A',
            'explanation': "'Io sono' is the first-person singular form of 'essere' (to be).",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in Italian?",
            'option_a': 'Blu',
            'option_b': 'Rosso',
            'option_c': 'Verde',
            'option_d': 'Giallo',
            'correct_answer': 'B',
            'explanation': "'Rosso' means 'red'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "How do you say 'I ate' in Italian?",
            'option_a': 'Mangio',
            'option_b': 'Ho mangiato',
            'option_c': 'Mangerò',
            'option_d': 'Mangiavo',
            'correct_answer': 'B',
            'explanation': "'Ho mangiato' is the passato prossimo form meaning 'I ate'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete the sentence: 'Ieri ___ al parco.' (Yesterday I went to the park.)",
            'option_a': 'vado',
            'option_b': 'sono andato',
            'option_c': 'andrò',
            'option_d': 'andavo',
            'correct_answer': 'B',
            'explanation': "'Sono andato' is the correct past-tense form with 'essere'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does 'Fa bel tempo' mean?",
            'option_a': "It's raining",
            'option_b': "It's windy",
            'option_c': "The weather is nice",
            'option_d': "It's snowing",
            'correct_answer': 'C',
            'explanation': "'Fa bel tempo' literally means 'It's nice weather.'",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Choose the correct comparative: 'Mio fratello è ___ di me.' (My brother is taller than me.)",
            'option_a': 'più alto',
            'option_b': 'più alta',
            'option_c': 'così alto',
            'option_d': 'alto',
            'correct_answer': 'A',
            'explanation': "Comparatives use 'più + adjective + di/che'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Complete with the subjunctive: 'Spero che tu ___ bene.' (I hope you are well.)",
            'option_a': 'sei',
            'option_b': 'stai',
            'option_c': 'stia',
            'option_d': 'sarai',
            'correct_answer': 'C',
            'explanation': "'Spero che' requires the present subjunctive: 'stia'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Which sentence correctly uses a conditional structure?",
            'option_a': 'Se ho soldi, compro una casa.',
            'option_b': 'Se avessi soldi, comprerei una casa.',
            'option_c': 'Quando avrò soldi, compro casa.',
            'option_d': 'Se ho soldi, comprato casa.',
            'correct_answer': 'B',
            'explanation': "Proper conditional pairs the imperfect subjunctive with the conditional.",
            'difficulty_points': 3,
        },
    ],
    'Japanese': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "What is the Japanese word for 'hello'?",
            'option_a': 'さようなら',
            'option_b': 'こんにちは',
            'option_c': 'ありがとう',
            'option_d': 'お願いします',
            'correct_answer': 'B',
            'explanation': "'こんにちは' (konnichiwa) is the standard daytime greeting.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in Japanese?",
            'option_a': 'ごめんなさい',
            'option_b': 'ありがとう',
            'option_c': 'こんばんは',
            'option_d': 'おはよう',
            'correct_answer': 'B',
            'explanation': "'ありがとう' (arigatou) means 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which phrase means 'I am'?",
            'option_a': '私は〜です',
            'option_b': 'あなたは〜です',
            'option_c': '彼は〜です',
            'option_d': '私たちは〜です',
            'correct_answer': 'A',
            'explanation': "'私は〜です' (watashi wa ~ desu) expresses 'I am ...'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in Japanese?",
            'option_a': '青',
            'option_b': '赤',
            'option_c': '緑',
            'option_d': '黄色',
            'correct_answer': 'B',
            'explanation': "'赤' (aka) means 'red'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "How do you say 'I ate' in Japanese?",
            'option_a': '食べます',
            'option_b': '食べました',
            'option_c': '食べる',
            'option_d': '食べている',
            'correct_answer': 'B',
            'explanation': "'食べました' (tabemashita) is the past tense 'I ate'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete the sentence: '昨日、私は公園に ___ .' (Yesterday I went to the park.)",
            'option_a': '行きます',
            'option_b': '行きました',
            'option_c': '行く',
            'option_d': '行っている',
            'correct_answer': 'B',
            'explanation': "'行きました' (ikimashita) is the polite past form of 'go'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does 'いい天気です' mean?",
            'option_a': "It's raining",
            'option_b': "It's windy",
            'option_c': "The weather is nice",
            'option_d': "It's snowing",
            'correct_answer': 'C',
            'explanation': "'いい天気です' (ii tenki desu) means 'The weather is nice.'",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Which sentence means 'My brother is taller than me'?",
            'option_a': '兄は私より背が高い',
            'option_b': '兄は私と同じ背です',
            'option_c': '兄は私より背が低い',
            'option_d': '兄の背は変わりません',
            'correct_answer': 'A',
            'explanation': "“兄は私より背が高い” literally means 'My older brother is taller than me.'",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Choose the polite request meaning 'Could you help me?'",
            'option_a': '手伝っていただけますか？',
            'option_b': '手伝ったことがあります',
            'option_c': '手伝いません',
            'option_d': '手伝えばいいです',
            'correct_answer': 'A',
            'explanation': "'手伝っていただけますか？' is a formal way to ask for help.",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Complete the conditional: '時間があれば、友達に ___ .' (If I have time, I will meet my friends.)",
            'option_a': '会います',
            'option_b': '会った',
            'option_c': '会いません',
            'option_d': '会える',
            'correct_answer': 'A',
            'explanation': "'会います' (aimasu) expresses the resulting action 'will meet'.",
            'difficulty_points': 3,
        },
    ],
    'Chinese': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "What is the Chinese word for 'hello'?",
            'option_a': '谢谢',
            'option_b': '你好',
            'option_c': '再见',
            'option_d': '请',
            'correct_answer': 'B',
            'explanation': "'你好' (nǐ hǎo) is the standard greeting meaning 'hello'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in Chinese?",
            'option_a': '你好',
            'option_b': '谢谢',
            'option_c': '请',
            'option_d': '对不起',
            'correct_answer': 'B',
            'explanation': "'谢谢' (xièxie) means 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which phrase means 'I am'?",
            'option_a': '我是',
            'option_b': '你是',
            'option_c': '他是',
            'option_d': '她是',
            'correct_answer': 'A',
            'explanation': "'我是' (wǒ shì) literally means 'I am'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in Chinese?",
            'option_a': '桌子',
            'option_b': '红色',
            'option_c': '书',
            'option_d': '窗户',
            'correct_answer': 'B',
            'explanation': "'红色' (hóngsè) means 'red'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "How do you say 'I ate' in Chinese?",
            'option_a': '我吃',
            'option_b': '我吃了',
            'option_c': '我要吃',
            'option_d': '我在吃',
            'correct_answer': 'B',
            'explanation': "'我吃了' (wǒ chī le) is the past/perfect form 'I ate'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete the sentence: '昨天我___公园。' (Yesterday I went to the park.)",
            'option_a': '去',
            'option_b': '去了',
            'option_c': '去过',
            'option_d': '去着',
            'correct_answer': 'B',
            'explanation': "'去了' (qù le) is the completed-action form of 'go'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does '今天天气很好' mean?",
            'option_a': "It's raining today",
            'option_b': "The weather is nice today",
            'option_c': "It's very cold today",
            'option_d': "It's snowing today",
            'correct_answer': 'B',
            'explanation': "'今天天气很好' (jīntiān tiānqì hěn hǎo) means 'The weather is very good today.'",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Choose the correct comparative: '我哥哥比我___.' (My brother is taller than me.)",
            'option_a': '高',
            'option_b': '矮',
            'option_c': '一样高',
            'option_d': '不高',
            'correct_answer': 'A',
            'explanation': "'比' marks a comparison; '高' (tall) completes the sentence.",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Which expression means 'I hope you are well'?",
            'option_a': '希望你一切都好',
            'option_b': '我很好',
            'option_c': '天气很好',
            'option_d': '请进',
            'correct_answer': 'A',
            'explanation': "'希望你一切都好' literally means 'I hope everything is good with you.'",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Which sentence correctly uses a conditional structure?",
            'option_a': '如果我有钱，我就买房子。',
            'option_b': '我有钱，就买房子。',
            'option_c': '我有钱，就买了房子。',
            'option_d': '如果我有钱，我买房子了。',
            'correct_answer': 'A',
            'explanation': "'如果..., 就...' is the standard conditional pattern in Chinese.",
            'difficulty_points': 3,
        },
    ],
    'Portuguese': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "What is the Portuguese word for 'hello'?",
            'option_a': 'Adeus',
            'option_b': 'Olá',
            'option_c': 'Obrigado',
            'option_d': 'Por favor',
            'correct_answer': 'B',
            'explanation': "'Olá' is the standard greeting meaning 'hello'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in Portuguese (masculine)?",
            'option_a': 'Obrigado',
            'option_b': 'Desculpa',
            'option_c': 'Por favor',
            'option_d': 'Bom dia',
            'correct_answer': 'A',
            'explanation': "'Obrigado' is used by male speakers to say 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which phrase means 'I am'?",
            'option_a': 'Eu sou',
            'option_b': 'Tu és',
            'option_c': 'Ele é',
            'option_d': 'Nós somos',
            'correct_answer': 'A',
            'explanation': "'Eu sou' is the first-person singular of 'ser'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in Portuguese?",
            'option_a': 'Mesa',
            'option_b': 'Vermelho',
            'option_c': 'Livro',
            'option_d': 'Janela',
            'correct_answer': 'B',
            'explanation': "'Vermelho' means 'red'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "How do you say 'I ate' in Portuguese?",
            'option_a': 'Eu como',
            'option_b': 'Eu comerei',
            'option_c': 'Eu comi',
            'option_d': 'Eu comia',
            'correct_answer': 'C',
            'explanation': "'Eu comi' is the preterite form meaning 'I ate'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete the sentence: 'Ontem eu ___ à praia.' (Yesterday I went to the beach.)",
            'option_a': 'Vou',
            'option_b': 'Fui',
            'option_c': 'Irei',
            'option_d': 'Ia',
            'correct_answer': 'B',
            'explanation': "'Fui' is the past tense of 'ir' (to go).",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does 'Está calor hoje' mean?",
            'option_a': "It's cold today",
            'option_b': "It's warm today",
            'option_c': "It's raining today",
            'option_d': "It's windy today",
            'correct_answer': 'B',
            'explanation': "'Está calor hoje' describes warm weather.",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Choose the correct comparative: 'Meu irmão é ___ do que eu.' (My brother is taller than me.)",
            'option_a': 'mais alto',
            'option_b': 'mais alta',
            'option_c': 'tão alto',
            'option_d': 'alto',
            'correct_answer': 'A',
            'explanation': "Comparatives use 'mais + adjective + que'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Complete with the subjunctive: 'Espero que você ___ bem.'",
            'option_a': 'está',
            'option_b': 'esteja',
            'option_c': 'estar',
            'option_d': 'estará',
            'correct_answer': 'B',
            'explanation': "'Espero que' triggers the present subjunctive 'esteja'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Which sentence correctly uses a conditional structure?",
            'option_a': 'Se eu tenho tempo, viajaria.',
            'option_b': 'Se eu tivesse dinheiro, compraria uma casa.',
            'option_c': 'Quando eu tenho tempo, eu compraria.',
            'option_d': 'Eu compraria se eu tenho tempo.',
            'correct_answer': 'B',
            'explanation': "Proper conditional pairs 'se' + imperfect subjunctive with conditional.",
            'difficulty_points': 3,
        },
    ],
    'Russian': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "What is the Russian word for 'hello'?",
            'option_a': 'Пока',
            'option_b': 'Здравствуйте',
            'option_c': 'Спасибо',
            'option_d': 'Пожалуйста',
            'correct_answer': 'B',
            'explanation': "'Здравствуйте' (Zdravstvuyte) is a formal greeting meaning 'hello'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in Russian?",
            'option_a': 'Здравствуйте',
            'option_b': 'Пожалуйста',
            'option_c': 'Спасибо',
            'option_d': 'Извините',
            'correct_answer': 'C',
            'explanation': "'Спасибо' (Spasibo) means 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which phrase means 'I am a student'?",
            'option_a': 'Я студент',
            'option_b': 'Ты студент',
            'option_c': 'Он студент',
            'option_d': 'Мы студенты',
            'correct_answer': 'A',
            'explanation': "'Я студент' (Ya student) means 'I am a student.'",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in Russian?",
            'option_a': 'Стол',
            'option_b': 'Красный',
            'option_c': 'Книга',
            'option_d': 'Окно',
            'correct_answer': 'B',
            'explanation': "'Красный' (krasnyy) means 'red'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "How do you say 'I ate' in Russian?",
            'option_a': 'Я ем',
            'option_b': 'Я ел',
            'option_c': 'Я съем',
            'option_d': 'Я ел бы',
            'correct_answer': 'B',
            'explanation': "'Я ел' (Ya el) is the past tense 'I ate' (masculine form).",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete the sentence: 'Вчера я ___ в парк.' (Yesterday I went to the park.)",
            'option_a': 'иду',
            'option_b': 'пошёл',
            'option_c': 'пойду',
            'option_d': 'ходил',
            'correct_answer': 'B',
            'explanation': "'пошёл' is the past tense (masculine) of 'to go' by foot.",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does 'Сегодня хорошая погода' mean?",
            'option_a': "It's raining today",
            'option_b': "The weather is nice today",
            'option_c': "It's very cold today",
            'option_d': "It's snowing today",
            'correct_answer': 'B',
            'explanation': "The phrase literally means 'Today the weather is good.'",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Choose the correct comparative: 'Мой брат ___ меня.' (My brother is taller than me.)",
            'option_a': 'выше',
            'option_b': 'ниже',
            'option_c': 'такой же',
            'option_d': 'маленький',
            'correct_answer': 'A',
            'explanation': "'Выше' is the comparative form of 'tall'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Complete the sentence: 'Я хочу, чтобы ты ___ рано.' (I want you to come early.)",
            'option_a': 'приходит',
            'option_b': 'пришёл',
            'option_c': 'придёт',
            'option_d': 'приходил',
            'correct_answer': 'B',
            'explanation': "After 'чтобы' you typically use the past tense form 'пришёл'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Which sentence correctly uses a conditional structure?",
            'option_a': 'Если бы у меня были деньги, я бы купил дом.',
            'option_b': 'Если у меня деньги, я покупаю дом.',
            'option_c': 'Когда будут деньги, куплю дом.',
            'option_d': 'Если есть деньги, купил дом.',
            'correct_answer': 'A',
            'explanation': "Russian unreal conditionals use 'Если бы... я бы...'.",
            'difficulty_points': 3,
        },
    ],
    'Arabic': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "What is the Arabic word for 'hello'?",
            'option_a': 'وداعاً',
            'option_b': 'مرحبًا',
            'option_c': 'شكرًا',
            'option_d': 'من فضلك',
            'correct_answer': 'B',
            'explanation': "'مرحبًا' (marhaban) is a common way to say 'hello'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in Arabic?",
            'option_a': 'عفوًا',
            'option_b': 'شكرًا',
            'option_c': 'مرحبا',
            'option_d': 'آسف',
            'correct_answer': 'B',
            'explanation': "'شكرًا' (shukran) means 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which phrase means 'I am'?",
            'option_a': 'أنا',
            'option_b': 'أنت',
            'option_c': 'هو',
            'option_d': 'نحن',
            'correct_answer': 'A',
            'explanation': "'أنا' (ana) means 'I am'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in Arabic?",
            'option_a': 'كتاب',
            'option_b': 'أحمر',
            'option_c': 'باب',
            'option_d': 'شجرة',
            'correct_answer': 'B',
            'explanation': "'أحمر' (ahmar) means 'red'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "How do you say 'I ate' in Arabic?",
            'option_a': 'آكل',
            'option_b': 'سآكل',
            'option_c': 'أكلتُ',
            'option_d': 'كنت آكل',
            'correct_answer': 'C',
            'explanation': "'أكلتُ' (akal-tu) is the past tense 'I ate'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete the sentence: 'ذهبتُ أمس إلى ___.' (Yesterday I went to the park.)",
            'option_a': 'المدرسة',
            'option_b': 'الحديقة',
            'option_c': 'البيت',
            'option_d': 'المكتبة',
            'correct_answer': 'B',
            'explanation': "'الحديقة' (al-hadiqa) means 'the park'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does 'الطقس جميل اليوم' mean?",
            'option_a': "It's raining today",
            'option_b': "The weather is nice today",
            'option_c': "It's very cold today",
            'option_d': "It's snowing today",
            'correct_answer': 'B',
            'explanation': "The phrase literally means 'The weather is beautiful today.'",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Choose the correct comparative: 'أخي ___ مني.' (My brother is taller than me.)",
            'option_a': 'أطول',
            'option_b': 'أقصر',
            'option_c': 'مثل',
            'option_d': 'أصغر',
            'correct_answer': 'A',
            'explanation': "'أطول' (atwal) is the comparative form of 'tall'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Complete the sentence: 'أتمنى أن ___ بخير.' (I hope you are well.)",
            'option_a': 'تكون',
            'option_b': 'كان',
            'option_c': 'ستكون',
            'option_d': 'كنت',
            'correct_answer': 'A',
            'explanation': "'تكون' (takun) is the present subjunctive form meaning 'you are'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Which sentence correctly uses a conditional structure?",
            'option_a': 'لو كان لدي مال، لاشتريتُ بيتًا.',
            'option_b': 'إذا لدي مال، أشتري بيتًا.',
            'option_c': 'كان لدي مال، اشتريت بيتًا.',
            'option_d': 'عندما لدي مال، أشتري بيت.',
            'correct_answer': 'A',
            'explanation': "'لو... لاشتريتُ...' forms the classical conditional structure in Arabic.",
            'difficulty_points': 3,
        },
    ],
    'German': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "What is the German word for 'hello'?",
            'option_a': 'Hallo',
            'option_b': 'Tschüss',
            'option_c': 'Danke',
            'option_d': 'Bitte',
            'correct_answer': 'A',
            'explanation': "'Hallo' is the common informal greeting meaning 'hello'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in German?",
            'option_a': 'Bitte',
            'option_b': 'Auf Wiedersehen',
            'option_c': 'Guten Morgen',
            'option_d': 'Danke',
            'correct_answer': 'D',
            'explanation': "'Danke' translates to 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which phrase means 'I am'?",
            'option_a': 'Ich bin',
            'option_b': 'Du bist',
            'option_c': 'Er ist',
            'option_d': 'Wir sind',
            'correct_answer': 'A',
            'explanation': "'Ich bin' is the first person singular of 'sein' (to be).",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in German?",
            'option_a': 'Buch',
            'option_b': 'Rot',
            'option_c': 'Stuhl',
            'option_d': 'Fenster',
            'correct_answer': 'B',
            'explanation': "'Rot' means 'red'. The other words mean book, chair, and window.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "How do you say 'I ate' in German?",
            'option_a': 'Ich esse',
            'option_b': 'Ich habe gegessen',
            'option_c': 'Ich werde essen',
            'option_d': 'Ich aß',
            'correct_answer': 'B',
            'explanation': "'Ich habe gegessen' is the perfect tense commonly used for past actions.",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete: 'Morgen ___ ich ins Kino gehen.' (Tomorrow I will go to the cinema.)",
            'option_a': 'gehe',
            'option_b': 'ging',
            'option_c': 'werde',
            'option_d': 'bin gegangen',
            'correct_answer': 'C',
            'explanation': "Future tense in German often uses 'werden' + infinitive.",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does 'Es ist warm' mean?",
            'option_a': "It's raining",
            'option_b': "It's windy",
            'option_c': "It's warm",
            'option_d': "It's cloudy",
            'correct_answer': 'C',
            'explanation': "'Es ist warm' literally means 'It is warm'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Choose the correct comparative: 'Mein Bruder ist ___ als ich.' (My brother is taller than me.)",
            'option_a': 'größer',
            'option_b': 'groß',
            'option_c': 'am groß',
            'option_d': 'größte',
            'correct_answer': 'A',
            'explanation': "Comparatives add '‑er': 'größer als'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Which sentence has the correct subordinate clause word order?",
            'option_a': 'Ich weiß, du kommst morgen.',
            'option_b': 'Ich weiß, dass du morgen kommst.',
            'option_c': 'Ich weiß dass du kommst morgen.',
            'option_d': 'Ich weiß, dass du kommst morgen.',
            'correct_answer': 'B',
            'explanation': "Subordinate clauses send the verb to the end: 'dass du morgen kommst'.",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Which conditional sentence is correct?",
            'option_a': 'Wenn ich Zeit habe, würde ich mehr lesen.',
            'option_b': 'Wenn ich Zeit hätte, würde ich mehr lesen.',
            'option_c': 'Wenn ich Zeit hätte, ich würde mehr lesen.',
            'option_d': 'Wenn ich Zeit habe würde ich mehr lesen.',
            'correct_answer': 'B',
            'explanation': "Unreal conditionals use 'hätte' + 'würde' construction.",
            'difficulty_points': 3,
        },
    ],
    'Korean': [
        {
            'question_number': 1,
            'difficulty_level': 'A1',
            'question_text': "Which expression means 'hello' in Korean?",
            'option_a': '안녕하세요',
            'option_b': '감사합니다',
            'option_c': '잘 자요',
            'option_d': '미안합니다',
            'correct_answer': 'A',
            'explanation': "'안녕하세요' (annyeonghaseyo) is the polite way to say hello.",
            'difficulty_points': 1,
        },
        {
            'question_number': 2,
            'difficulty_level': 'A1',
            'question_text': "How do you say 'thank you' in Korean?",
            'option_a': '사랑해요',
            'option_b': '괜찮아요',
            'option_c': '감사합니다',
            'option_d': '안녕히 가세요',
            'correct_answer': 'C',
            'explanation': "'감사합니다' (gamsahamnida) means 'thank you'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 3,
            'difficulty_level': 'A1',
            'question_text': "Which sentence means 'I am a student'?",
            'option_a': '저는 학생입니다',
            'option_b': '저는 선생님입니다',
            'option_c': '저는 친구입니다',
            'option_d': '저는 회사원입니다',
            'correct_answer': 'A',
            'explanation': "'저는 학생입니다' translates to 'I am a student'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 4,
            'difficulty_level': 'A1',
            'question_text': "Which of these is a color in Korean?",
            'option_a': '책',
            'option_b': '파란색',
            'option_c': '학교',
            'option_d': '친구',
            'correct_answer': 'B',
            'explanation': "'파란색' (paran-saek) means 'blue'.",
            'difficulty_points': 1,
        },
        {
            'question_number': 5,
            'difficulty_level': 'A2',
            'question_text': "Which sentence means 'I ate rice'?",
            'option_a': '밥을 먹었어요',
            'option_b': '밥을 먹을 거예요',
            'option_c': '밥을 먹고 있어요',
            'option_d': '밥을 먹지 않아요',
            'correct_answer': 'A',
            'explanation': "'먹었어요' is the past tense meaning 'ate'.",
            'difficulty_points': 2,
        },
        {
            'question_number': 6,
            'difficulty_level': 'A2',
            'question_text': "Complete: '내일 저는 도서관에 ___.' (Tomorrow I will go to the library.)",
            'option_a': '갑니다',
            'option_b': '가요',
            'option_c': '갈 거예요',
            'option_d': '갔어요',
            'correct_answer': 'C',
            'explanation': "'갈 거예요' indicates future intention ('will go').",
            'difficulty_points': 2,
        },
        {
            'question_number': 7,
            'difficulty_level': 'A2',
            'question_text': "What does '날씨가 좋아요' mean?",
            'option_a': 'It is raining',
            'option_b': 'It is too hot',
            'option_c': 'The weather is nice',
            'option_d': 'It is snowing',
            'correct_answer': 'C',
            'explanation': "'좋아요' means 'is good'—the weather is pleasant.",
            'difficulty_points': 2,
        },
        {
            'question_number': 8,
            'difficulty_level': 'B1',
            'question_text': "Fill in the blank: '한국어를 ___ 공부하면 더 잘하게 돼요.' (If you study Korean ___, you get better.)",
            'option_a': '꾸준히',
            'option_b': '빨리',
            'option_c': '조용히',
            'option_d': '갑자기',
            'correct_answer': 'A',
            'explanation': "'꾸준히' means 'consistently', fitting the conditional meaning.",
            'difficulty_points': 3,
        },
        {
            'question_number': 9,
            'difficulty_level': 'B1',
            'question_text': "Choose the polite request meaning 'Could you help me?'",
            'option_a': '도와줄래?',
            'option_b': '도와주세요',
            'option_c': '도와줄 거야',
            'option_d': '도와준다',
            'correct_answer': 'B',
            'explanation': "'도와주세요' is the standard polite request form.",
            'difficulty_points': 3,
        },
        {
            'question_number': 10,
            'difficulty_level': 'B1',
            'question_text': "Complete the conditional: '시간이 있으면 친구를 ___.' (If I have time, I will meet my friend.)",
            'option_a': '만났어요',
            'option_b': '만나요',
            'option_c': '만날 거예요',
            'option_d': '만나고 있어요',
            'correct_answer': 'C',
            'explanation': "'만날 거예요' expresses the future result of the condition.",
            'difficulty_points': 3,
        },
    ],
}


def build_lesson_blueprints(language: str) -> List[Dict]:
    """
    Generate lesson metadata, flashcards, and quiz questions for a language.

    Args:
        language: English language name (e.g., 'French').

    Returns:
        List of dicts describing lessons ready to persist.
    """
    blueprints: List[Dict] = []

    for key, config in LESSON_CARD_DATA.items():
        cards_for_language = []
        for idx, card in enumerate(config['cards'], start=1):
            translation = card['translations'].get(language)
            if not translation:
                continue
            cards_for_language.append({
                'order': idx,
                'front_text': card['front'],
                'back_text': translation,
                'image_url': '',
            })

        if not cards_for_language:
            continue

        if language.lower() == DEFAULT_LANGUAGE.lower():
            lesson_slug = config['slug']
        else:
            lesson_slug = f"{config['slug']}-{language.lower()}"

        blueprint = {
            'key': key,
            'title': config['title_template'].format(language=language),
            'description': config['description_template'].format(language=language),
            'slug': lesson_slug,
            'language': language,
            'order': config['order'],
            'category': config['category'],
            'lesson_type': 'flashcard',
            'xp_value': config['xp_value'],
            'flashcards': cards_for_language,
            'quiz_questions': _build_quiz_questions(
                cards_for_language, language, key, config.get('quiz_count', len(cards_for_language))
            ),
        }
        blueprints.append(blueprint)

    return blueprints


def _build_quiz_questions(cards: List[Dict], language: str, key: str, quiz_count: int) -> List[Dict]:
    """Build deterministic quiz questions from the provided flashcards."""
    questions: List[Dict] = []
    subset = cards[:quiz_count]

    for order, card in enumerate(subset, start=1):
        distractors = [c['back_text'] for c in cards if c['back_text'] != card['back_text']]
        options = [card['back_text']] + distractors[:3]

        questions.append({
            'order': order,
            'question': f'What is "{card["front_text"]}" in {language}?',
            'options': options,
            'correct_index': 0,
        })

    return questions

