# Generated by Django 5.2.7 on 2025-10-27 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='For guest tracking', max_length=100)),
                ('language', models.CharField(default='Spanish', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_level', models.CharField(blank=True, choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate')], max_length=2)),
                ('total_score', models.IntegerField(default=0)),
                ('total_possible', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Attempt',
                'verbose_name_plural': 'Onboarding Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('language', models.CharField(default='Spanish', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate')], max_length=2)),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(help_text="Store 'A', 'B', 'C', or 'D'", max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty_points', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Onboarding Question',
                'verbose_name_plural': 'Onboarding Questions',
                'ordering': ['language', 'question_number'],
                'unique_together': {('language', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(help_text='A, B, C, or D', max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='home.onboardingattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='home.onboardingquestion')),
            ],
            options={
                'verbose_name': 'Onboarding Answer',
                'verbose_name_plural': 'Onboarding Answers',
                'ordering': ['question__question_number'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(blank=True, choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)')], help_text='CEFR proficiency level determined by onboarding assessment', max_length=2, null=True)),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_language', models.CharField(default='Spanish', max_length=50)),
                ('daily_goal_minutes', models.IntegerField(default=15)),
                ('learning_motivation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
