# Generated by Django 5.2.7 on 2025-10-29 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_onboardingattempt_onboardingquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB, PNG/JPG only)', null=True, upload_to=home.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
