# Generated by Django 5.2.7 on 2025-11-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lesson_flashcard_lessonattempt_lessonquizquestion'),
        ('home', '0003_userprofile_avatar_alter_userprofile_user'),
    ]

    operations = [
    ]
