# Generated by Django 5.1.13 on 2025-11-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20251103_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly identifier for template paths (e.g., 'shapes', 'colors')", max_length=200, null=True, unique=True),
        ),
    ]
