# Generated by Django 5.2.7 on 2025-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fix_shapes_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_level',
            field=models.IntegerField(default=1, help_text='Current level based on total XP earned'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_xp',
            field=models.IntegerField(default=0, help_text='Total experience points earned from completing lessons and quests'),
        ),
    ]
