# Generated by Django 5.2.7 on 2025-11-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_xp_leveling_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_level',
            field=models.PositiveIntegerField(default=1, help_text='Current level based on total XP earned'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, help_text='Total experience points earned from completing lessons and quests'),
        ),
    ]
