# Generated by Django 5.2.8 on 2025-11-13 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_xp_leveling_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quest_type', models.CharField(max_length=20)),
                ('xp_reward', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lesson')),
            ],
            options={
                'verbose_name': 'Daily Quest',
                'verbose_name_plural': 'Daily Quests',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.CharField(blank=True, max_length=200)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_index', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('difficulty_level', models.CharField(default='medium', max_length=10)),
                ('daily_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='home.dailyquest')),
            ],
            options={
                'verbose_name': 'Daily Quest Question',
                'verbose_name_plural': 'Daily Quest Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyQuestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=5)),
                ('correct_answers', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('daily_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='home.dailyquest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Daily Quest Attempt',
                'verbose_name_plural': 'User Daily Quest Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['date'], name='home_dailyq_date_910439_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyquestquestion',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 5)), name='valid_question_order'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquestquestion',
            unique_together={('daily_quest', 'order')},
        ),
        migrations.AddIndex(
            model_name='userdailyquestattempt',
            index=models.Index(fields=['user', '-started_at'], name='home_userda_user_id_d1ceb0_idx'),
        ),
        migrations.AddIndex(
            model_name='userdailyquestattempt',
            index=models.Index(fields=['daily_quest', 'is_completed'], name='home_userda_daily_q_874c6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdailyquestattempt',
            unique_together={('user', 'daily_quest')},
        ),
    ]
