# Generated by Django 5.2.8 on 2025-11-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_dailyquest_dailyquestquestion_userdailyquestattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(default='General', help_text='Category of lesson (e.g., Colors, Numbers, Shapes)', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('flashcard', 'Flashcard'), ('quiz', 'Quiz')], default='flashcard', help_text='Type of lesson content', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='xp_value',
            field=models.IntegerField(default=100, help_text='XP awarded for completing this lesson'),
        ),
    ]
