# Generated by Django 5.2.8 on 2025-11-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_use_positive_integer_for_xp_fields'),
        ('home', '0009_lesson_category_lesson_lesson_type_lesson_xp_value'),
    ]

    operations = [
    ]
