# Generated by Django 5.2.7 on 2025-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20251113_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyquest',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquest',
            unique_together={('date', 'quest_type')},
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['date', 'quest_type'], name='home_dailyq_date_6dc91d_idx'),
        ),
    ]
