# Generated by Django 5.2.7 on 2025-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_allow_multiple_quests_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Number of consecutive days with activity'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Last date user completed a lesson', null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Longest streak ever achieved'),
        ),
    ]
