# Generated by Django 5.2.7 on 2025-11-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_language_fields(apps, schema_editor):
    Lesson = apps.get_model('home', 'Lesson')
    LessonCompletion = apps.get_model('home', 'LessonCompletion')
    QuizResult = apps.get_model('home', 'QuizResult')

    lesson_languages = {
        str(lesson.id): lesson.language
        for lesson in Lesson.objects.all()
    }

    for completion in LessonCompletion.objects.all():
        language = lesson_languages.get(completion.lesson_id, 'Spanish')
        completion.language = language
        completion.save(update_fields=['language'])

    for quiz in QuizResult.objects.all():
        language = None
        if quiz.quiz_id.startswith('lesson_'):
            lesson_id = quiz.quiz_id.split('_', 1)[1]
            language = lesson_languages.get(lesson_id)
        elif quiz.quiz_id.startswith('onboarding_'):
            language = quiz.quiz_id.split('_', 1)[1]

        quiz.language = (language or 'Spanish').strip().title()
        quiz.save(update_fields=['language'])


def reset_language_fields(apps, schema_editor):
    LessonCompletion = apps.get_model('home', 'LessonCompletion')
    QuizResult = apps.get_model('home', 'QuizResult')
    LessonCompletion.objects.update(language='Spanish')
    QuizResult.objects.update(language='Spanish')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_add_streak_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncompletion',
            name='language',
            field=models.CharField(default='Spanish', help_text='Language associated with the completed lesson', max_length=50),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='language',
            field=models.CharField(default='Spanish', help_text='Language associated with the quiz content', max_length=50),
        ),
        migrations.RunPython(populate_language_fields, reset_language_fields),
        migrations.CreateModel(
            name='UserLanguageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('proficiency_level', models.CharField(blank=True, choices=[('A1', 'Beginner (A1)'), ('A2', 'Elementary (A2)'), ('B1', 'Intermediate (B1)')], max_length=2, null=True)),
                ('has_completed_onboarding', models.BooleanField(default=False)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_minutes_studied', models.IntegerField(default=0)),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_quizzes_taken', models.IntegerField(default=0)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Language Profile',
                'verbose_name_plural': 'User Language Profiles',
                'ordering': ['language'],
                'constraints': [models.UniqueConstraint(fields=('user', 'language'), name='unique_user_language_profile')],
            },
        ),
    ]
