# Generated by Django 5.2.7 on 2025-11-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_seed_global_lessons'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyquest',
            name='home_dailyq_date_6dc91d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailyquest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='language',
            field=models.CharField(db_index=True, default='Spanish', help_text='Language this challenge targets (matches user profile language)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquest',
            unique_together={('date', 'language')},
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['date', 'language'], name='home_dailyq_date_c83526_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['language'], name='home_dailyq_languag_c3835a_idx'),
        ),
    ]
