# Generated by Django 5.2.7 on 2025-11-17 01:07

from django.db import migrations, models


def dedupe_dailyquests(apps, schema_editor):
    DailyQuest = apps.get_model('home', 'DailyQuest')
    seen = set()
    for quest in DailyQuest.objects.order_by('date', 'language', 'id'):
        language = quest.language or 'Spanish'
        if quest.language != language:
            quest.language = language
            quest.save(update_fields=['language'])

        key = (quest.date, language)
        if key in seen:
            quest.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):
    # Disable the default transaction wrapper so that the data cleanup step
    # commits before we try to add the new unique constraint/indexes. Without
    # this, PostgreSQL can complain about pending trigger events when we attempt
    # to ALTER TABLE right after deleting duplicate quests.
    atomic = False

    dependencies = [
        ('home', '0016_seed_global_lessons'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyquest',
            name='home_dailyq_date_6dc91d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dailyquest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyquest',
            name='language',
            field=models.CharField(db_index=True, default='Spanish', help_text='Language this challenge targets (matches user profile language)', max_length=50),
        ),
        migrations.RunPython(dedupe_dailyquests, migrations.RunPython.noop, atomic=False),
        migrations.AlterUniqueTogether(
            name='dailyquest',
            unique_together={('date', 'language')},
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['date', 'language'], name='home_dailyq_date_c83526_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyquest',
            index=models.Index(fields=['language'], name='home_dailyq_languag_c3835a_idx'),
        ),
    ]
