# Generated by Django 5.2.7 on 2025-11-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_dailyquest_home_dailyq_date_6dc91d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_challenge_language',
            field=models.CharField(blank=True, help_text='Locked daily challenge language for the current day', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_challenge_language_date',
            field=models.DateField(blank=True, help_text='Date the daily challenge language was last locked', null=True),
        ),
    ]
