# Generated by Django 5.2.8 on 2025-11-29 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def convert_proficiency_level_field(apps, schema_editor):
    """
    Convert proficiency_level from CharField to IntegerField.
    
    Handles both PostgreSQL (production) and SQLite (tests) databases.
    Converts CEFR strings (A1, A2, B1) to integers (1, 2, 3).
    """
    from django.db import connection
    import logging
    
    logger = logging.getLogger(__name__)
    vendor = connection.vendor
    
    # Mapping from CEFR string to integer
    cefr_to_int = {'A1': 1, 'A2': 2, 'B1': 3}
    
    with connection.cursor() as cursor:
        if vendor == 'postgresql':
            # PostgreSQL: Two-step conversion to avoid type casting errors
            for table in ['home_userlanguageprofile', 'home_userprofile']:
                try:
                    # First, check if the column exists and what type it is
                    cursor.execute("""
                        SELECT data_type 
                        FROM information_schema.columns 
                        WHERE table_name = %s AND column_name = 'proficiency_level'
                    """, [table])
                    result = cursor.fetchone()
                    
                    # Check if column exists at all
                    if not result:
                        logger.info(f"Column {table}.proficiency_level does not exist, skipping conversion")
                        continue
                    
                    current_type = result[0]
                    
                    if current_type == 'integer':
                        # Column is already integer, but check if there are any string values in the data
                        # This can happen if a previous migration attempt partially succeeded
                        logger.info(f"Column {table}.proficiency_level is already integer, checking for string values...")
                        try:
                            # Try to find any string values that shouldn't be there
                            cursor.execute(f"""
                                SELECT COUNT(*) FROM {table} 
                                WHERE proficiency_level IS NOT NULL 
                                AND proficiency_level::text IN ('A1', 'A2', 'B1')
                            """)
                            count = cursor.fetchone()[0]
                            if count > 0:
                                logger.info(f"Found {count} string values in integer column, converting them...")
                                # Update string values to integers
                                cursor.execute(f"""
                                    UPDATE {table}
                                    SET proficiency_level = CASE
                                        WHEN proficiency_level::text = 'A1' THEN 1
                                        WHEN proficiency_level::text = 'A2' THEN 2
                                        WHEN proficiency_level::text = 'B1' THEN 3
                                        ELSE proficiency_level
                                    END
                                    WHERE proficiency_level::text IN ('A1', 'A2', 'B1')
                                """)
                                logger.info(f"Updated {count} string values to integers")
                            else:
                                logger.info(f"Column {table}.proficiency_level is already integer with valid data")
                        except Exception as check_error:
                            # If the check fails, assume the column is truly integer and skip
                            logger.info(f"Column {table}.proficiency_level appears to be integer, skipping conversion")
                        continue
                    
                    # Column exists and is not integer, convert it using two-step approach
                    logger.info(f"Converting {table}.proficiency_level from {current_type} to integer")
                    
                    # STEP 1: Update all string values to their numeric string equivalents
                    # This ensures all data is in a format that can be converted to integer
                    logger.info(f"Step 1: Updating string values in {table}.proficiency_level...")
                    cursor.execute(f"""
                        UPDATE {table}
                        SET proficiency_level = CASE
                            WHEN proficiency_level::text = 'A1' THEN '1'
                            WHEN proficiency_level::text = 'A2' THEN '2'
                            WHEN proficiency_level::text = 'B1' THEN '3'
                            WHEN proficiency_level::text ~ '^[0-9]+$' THEN proficiency_level::text
                            ELSE NULL
                        END
                        WHERE proficiency_level IS NOT NULL
                    """)
                    
                    # STEP 2: Now alter the column type to INTEGER
                    # Since all values are now numeric strings or NULL, this conversion is safe
                    logger.info(f"Step 2: Altering column type to INTEGER for {table}.proficiency_level...")
                    cursor.execute(f"""
                        ALTER TABLE {table}
                        ALTER COLUMN proficiency_level TYPE INTEGER
                        USING CASE
                            WHEN proficiency_level::text ~ '^[0-9]+$' THEN proficiency_level::text::INTEGER
                            ELSE NULL
                        END
                    """)
                    logger.info(f"Successfully converted {table}.proficiency_level to integer")
                except Exception as e:
                    # Log the error with more context and re-raise it
                    logger.error(f"Error converting {table}.proficiency_level: {e}")
                    # Try to get sample data for debugging
                    try:
                        cursor.execute(f"SELECT proficiency_level FROM {table} WHERE proficiency_level IS NOT NULL LIMIT 5")
                        sample = cursor.fetchall()
                        logger.error(f"Sample values in {table}.proficiency_level: {sample}")
                    except:
                        pass
                    raise
        
        elif vendor == 'sqlite':
            # SQLite: Create new column, copy data, drop old, rename new
            for table in ['home_userlanguageprofile', 'home_userprofile']:
                # Step 1: Create new INTEGER column
                cursor.execute(f"ALTER TABLE {table} ADD COLUMN proficiency_level_new INTEGER")
                
                # Step 2: Copy and convert data
                cursor.execute(f"SELECT id, proficiency_level FROM {table}")
                rows = cursor.fetchall()
                
                for row_id, old_value in rows:
                    if old_value is None:
                        new_value = None
                    elif old_value in cefr_to_int:
                        new_value = cefr_to_int[old_value]
                    elif isinstance(old_value, str) and old_value.isdigit():
                        new_value = int(old_value)
                    else:
                        new_value = None
                    
                    cursor.execute(
                        f"UPDATE {table} SET proficiency_level_new = ? WHERE id = ?",
                        [new_value, row_id]
                    )
                
                # Step 3: Drop old column
                cursor.execute(f"ALTER TABLE {table} DROP COLUMN proficiency_level")
                
                # Step 4: Rename new column
                cursor.execute(f"ALTER TABLE {table} RENAME COLUMN proficiency_level_new TO proficiency_level")
        
        else:
            # Fallback: Use Django ORM (slower but universal)
            UserProfile = apps.get_model('home', 'UserProfile')
            UserLanguageProfile = apps.get_model('home', 'UserLanguageProfile')
            
            for profile in UserProfile.objects.exclude(proficiency_level__isnull=True):
                if isinstance(profile.proficiency_level, str):
                    profile.proficiency_level = cefr_to_int.get(profile.proficiency_level.upper(), None)
                    profile.save(update_fields=['proficiency_level'])
            
            for lang_profile in UserLanguageProfile.objects.exclude(proficiency_level__isnull=True):
                if isinstance(lang_profile.proficiency_level, str):
                    lang_profile.proficiency_level = cefr_to_int.get(lang_profile.proficiency_level.upper(), None)
                    lang_profile.save(update_fields=['proficiency_level'])


def reverse_convert_proficiency_level(apps, schema_editor):
    """
    Reverse conversion (for rollback) - converts integers back to CEFR strings.
    Only maps 1-3 back to A1-B1, other values become NULL.
    """
    from django.db import connection
    
    vendor = connection.vendor
    int_to_cefr = {1: 'A1', 2: 'A2', 3: 'B1'}
    
    with connection.cursor() as cursor:
        if vendor == 'postgresql':
            for table in ['home_userlanguageprofile', 'home_userprofile']:
                cursor.execute(f"""
                    ALTER TABLE {table}
                    ALTER COLUMN proficiency_level TYPE VARCHAR(2)
                    USING CASE
                        WHEN proficiency_level = 1 THEN 'A1'
                        WHEN proficiency_level = 2 THEN 'A2'
                        WHEN proficiency_level = 3 THEN 'B1'
                        ELSE NULL
                    END;
                """)
        
        elif vendor == 'sqlite':
            for table in ['home_userlanguageprofile', 'home_userprofile']:
                cursor.execute(f"ALTER TABLE {table} ADD COLUMN proficiency_level_old VARCHAR(2)")
                
                cursor.execute(f"SELECT id, proficiency_level FROM {table}")
                rows = cursor.fetchall()
                
                for row_id, old_value in rows:
                    new_value = int_to_cefr.get(old_value) if old_value in int_to_cefr else None
                    cursor.execute(
                        f"UPDATE {table} SET proficiency_level_old = ? WHERE id = ?",
                        [new_value, row_id]
                    )
                
                cursor.execute(f"ALTER TABLE {table} DROP COLUMN proficiency_level")
                cursor.execute(f"ALTER TABLE {table} RENAME COLUMN proficiency_level_old TO proficiency_level")
        
        else:
            UserProfile = apps.get_model('home', 'UserProfile')
            UserLanguageProfile = apps.get_model('home', 'UserLanguageProfile')
            
            for profile in UserProfile.objects.exclude(proficiency_level__isnull=True):
                if isinstance(profile.proficiency_level, int):
                    profile.proficiency_level = int_to_cefr.get(profile.proficiency_level)
                    profile.save(update_fields=['proficiency_level'])
            
            for lang_profile in UserLanguageProfile.objects.exclude(proficiency_level__isnull=True):
                if isinstance(lang_profile.proficiency_level, int):
                    lang_profile.proficiency_level = int_to_cefr.get(lang_profile.proficiency_level)
                    lang_profile.save(update_fields=['proficiency_level'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_userprofile_daily_challenge_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('conversation', 'Conversation'), ('reading', 'Reading'), ('listening', 'Listening')], help_text='Skill category identifier', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Detailed description of what this skill covers')),
                ('icon', models.CharField(help_text='Emoji icon for UI display (e.g., 📚, 📝, 💬, 📖, 🎧)', max_length=10)),
                ('order', models.IntegerField(help_text='Order in lesson sequence within a level (1-5)')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        # Convert proficiency_level fields from CharField to IntegerField
        # The RunPython handles ALL database changes
        migrations.RunPython(
            convert_proficiency_level_field,
            reverse_convert_proficiency_level,
            atomic=False  # Set to False to allow the SQL to run outside transaction if needed
        ),
        # Update Django's state to match the database
        # NO database operations - RunPython already did everything
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='userlanguageprofile',
                    name='proficiency_level',
                    field=models.IntegerField(blank=True, help_text='Proficiency level 1-10 (1=absolute beginner, 10=advanced)', null=True),
                ),
                migrations.AlterField(
                    model_name='userprofile',
                    name='proficiency_level',
                    field=models.IntegerField(blank=True, help_text='Proficiency level 1-10 (1=absolute beginner, 10=advanced)', null=True),
                ),
                migrations.AlterField(
                    model_name='lesson',
                    name='difficulty_level',
                    field=models.IntegerField(default=1, help_text='Proficiency level 1-10 (1=absolute beginner, 10=advanced)'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text='Target language for this module', max_length=50)),
                ('proficiency_level', models.IntegerField(db_index=True, help_text='Level 1-10 (1=absolute beginner, 10=advanced)')),
                ('name', models.CharField(blank=True, help_text="Human-readable module name (e.g., 'Basics', 'Daily Life')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of topics covered in this level')),
                ('passing_score', models.IntegerField(default=85, help_text='Minimum percentage score to advance to next level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Module',
                'verbose_name_plural': 'Learning Modules',
                'ordering': ['language', 'proficiency_level'],
                'indexes': [models.Index(fields=['language', 'proficiency_level'], name='home_learni_languag_739b47_idx')],
                'unique_together': {('language', 'proficiency_level')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='skill_category',
            field=models.ForeignKey(blank=True, help_text='Skill this lesson teaches (vocabulary, grammar, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='home.skillcategory'),
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_completed', models.JSONField(default=list, help_text='List of completed lesson IDs')),
                ('test_attempts', models.IntegerField(default=0, help_text='Number of test attempts')),
                ('best_test_score', models.FloatField(default=0.0, help_text='Highest test score achieved (percentage)')),
                ('last_test_date', models.DateTimeField(blank=True, help_text='Timestamp of last test attempt', null=True)),
                ('is_module_complete', models.BooleanField(default=False, help_text='True when user passes test with 85%+')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when module was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='home.learningmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Module Progress',
                'verbose_name_plural': 'User Module Progress',
                'ordering': ['module__language', 'module__proficiency_level'],
                'indexes': [models.Index(fields=['user', 'is_module_complete'], name='home_usermo_user_id_dcbc00_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(help_text='Whether the user answered correctly')),
                ('user_answer', models.IntegerField(blank=True, help_text='Index of the answer the user selected', null=True)),
                ('time_taken_seconds', models.IntegerField(default=0, help_text='Time spent on this question')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attempts', to='home.lessonquizquestion')),
                ('skill_category', models.ForeignKey(blank=True, help_text='Skill category of the question (for analytics)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_attempts', to='home.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Question Attempt',
                'verbose_name_plural': 'User Question Attempts',
                'ordering': ['-answered_at'],
                'indexes': [models.Index(fields=['user', '-answered_at'], name='home_userqu_user_id_46918b_idx'), models.Index(fields=['user', 'skill_category'], name='home_userqu_user_id_fe5e57_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, help_text='Language this mastery applies to', max_length=50)),
                ('total_attempts', models.IntegerField(default=0, help_text='Total questions attempted for this skill')),
                ('correct_attempts', models.IntegerField(default=0, help_text='Total correct answers for this skill')),
                ('mastery_percentage', models.FloatField(default=0.0, help_text='Mastery level as percentage (0-100)')),
                ('last_practiced', models.DateTimeField(blank=True, help_text='Last time user practiced this skill', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mastery', to='home.skillcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill Mastery',
                'verbose_name_plural': 'User Skill Mastery',
                'ordering': ['language', 'skill_category__order'],
                'indexes': [models.Index(fields=['user', 'language'], name='home_usersk_user_id_c70d49_idx'), models.Index(fields=['user', 'language', 'mastery_percentage'], name='home_usersk_user_id_dbcf9c_idx')],
                'unique_together': {('user', 'skill_category', 'language')},
            },
        ),
    ]
