"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dv##fju3puju_bg4otr!stbh)0y==ql!cf=^o87+li&k&)u!1w')

# Development environment detection
# Set IS_DEVEDU=True environment variable when running in development proxies
# IMPORTANT: This must be explicitly set via environment variable - it will NOT
# auto-enable in production, ensuring CSRF and other security settings remain strict
#
# Accepts: 'True', 'true', '1', 'yes' as truthy values (case-insensitive)
# All other values (including unset) default to False
# Strips whitespace to handle ' true ', ' 1 ', etc.
import sys
IS_DEVEDU = os.environ.get('IS_DEVEDU', '').strip().lower() in ('true', '1', 'yes')

# SECURITY WARNING: don't run with debug turned on in production!
# Enable DEBUG in tests and development environments
# Also enable DEBUG by default for local development (can be overridden with DEBUG=False)
# SECURITY: Default to False for production safety
# Only enable DEBUG if explicitly set to 'True' in environment
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Force DEBUG=True in test mode
if 'pytest' in sys.modules or 'test' in sys.argv:
    DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "[::1]",
    "testserver",  # For Django test client
    "languagelearningplatform.org",     # Custom domain
    "www.languagelearningplatform.org", # Custom domain with www
    ".devedu.io",  # Allow all devedu.io subdomains
]

# Add development proxy hosts if IS_DEVEDU is set
if IS_DEVEDU:
    # Add specific host if provided
    devedu_host = os.environ.get('DEVEDU_HOST', '')
    if devedu_host:
        ALLOWED_HOSTS.append(devedu_host)
    # Also allow all hosts when in dev mode (needed for proxy forwarding)
    ALLOWED_HOSTS.append('*')

# Add Render.com host if RENDER environment variable exists
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    "home",  # Must be before django.contrib.admin to override admin templates
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Conditionally add Cloudinary apps only if credentials are configured
# This prevents 500 errors when Cloudinary is not set up in production
if os.environ.get('CLOUDINARY_CLOUD_NAME'):
    INSTALLED_APPS += [
        'cloudinary_storage',  # Cloudinary storage for media files
        'cloudinary',  # Cloudinary SDK
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.devedu_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL on Render, SQLite for local development
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Production: Use PostgreSQL from Render
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files configuration
# For development proxies - use STATIC_URL_PREFIX environment variable
if IS_DEVEDU:
    proxy_prefix = os.environ.get('STATIC_URL_PREFIX', '/proxy/8000')
    STATIC_URL = f'{proxy_prefix}/static/'
    # Don't use FORCE_SCRIPT_NAME - it causes double proxy prefix issues
    # Django will generate relative URLs which work fine through the proxy
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    # Relax CSRF for DevEDU (development only - not for production!)
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = 'Lax'
else:
    # For local development and production (Render)
    STATIC_URL = '/static/'

# Directory where collectstatic will collect static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# =============================================================================
# CLOUDINARY CONFIGURATION (for user-uploaded media files like avatars)
# =============================================================================
# Cloudinary provides free cloud storage for images with CDN delivery
# Free tier: 25GB storage, 25GB bandwidth/month (more than enough for college project)
#
# Required environment variables (set in Render dashboard):
# - CLOUDINARY_CLOUD_NAME: Your Cloudinary cloud name
# - CLOUDINARY_API_KEY: Your Cloudinary API key
# - CLOUDINARY_API_SECRET: Your Cloudinary API secret
#
# Get these from: https://cloudinary.com/console (free account)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# Media files configuration (user uploaded content - avatars, etc.)
# SECURITY CONSIDERATIONS:
# - MEDIA_ROOT stores user-uploaded files which should NEVER be directly web-accessible
# - Django serves media files via views in development (see config/urls.py)
# - In production, configure web server (nginx/Apache) to serve from MEDIA_ROOT with:
#   * Content-Type validation to prevent script execution
#   * X-Content-Type-Options: nosniff header
#   * No directory listings
#   * Separate domain/subdomain if possible (e.g., media.example.com)
# - DO NOT serve MEDIA_ROOT from the same path as STATIC_ROOT
# - Implement file type validation at upload (see home/forms.py)
# - Consider cloud storage (S3, Cloudinary) for production scalability

if IS_DEVEDU:
    # DevEDU proxy environment: Use STATIC_URL_PREFIX for media files
    # Default to /proxy/8000 if not set explicitly
    proxy_prefix = os.environ.get('STATIC_URL_PREFIX', '/proxy/8000')
    MEDIA_URL = f'{proxy_prefix}/media/'
else:
    # Local development and production: Standard media URL
    MEDIA_URL = '/media/'

# Directory where uploaded media files are stored
# WARNING: Ensure proper file permissions (not world-writable)
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration for efficient static file serving
# Use simpler storage for tests (avoids manifest file requirement)
import sys
if 'pytest' in sys.modules or 'test' in sys.argv:
    # Tests: Use filesystem storage for simplicity
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
elif CLOUDINARY_STORAGE.get('CLOUD_NAME'):
    # Production with Cloudinary: Use cloud storage for media files
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Local development: Use filesystem storage
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    "https://*.devedu.io",  # Allow all DevEDU subdomains by default
    "http://*.devedu.io",   # Also allow HTTP for development
]

# Add development proxy origins if IS_DEVEDU is set
if IS_DEVEDU:
    devedu_host = os.environ.get('DEVEDU_HOST', '')
    if devedu_host:
        CSRF_TRUSTED_ORIGINS.append(f'https://{devedu_host}')
        CSRF_TRUSTED_ORIGINS.append(f'http://{devedu_host}')
    # Set CSRF cookie path to root so it works with proxy prefix
    CSRF_COOKIE_PATH = '/'

# Add Render hostname to CSRF trusted origins
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')


# =============================================================================
# AUTHENTICATION SETTINGS
# =============================================================================

# Login/Logout redirect URLs
LOGIN_URL = 'login'  # Where to redirect if login is required
LOGIN_REDIRECT_URL = 'landing'  # Where to redirect after successful login
LOGOUT_REDIRECT_URL = 'landing'  # Where to redirect after logout

# =============================================================================
# EMAIL SETTINGS
# =============================================================================

# Email configuration for password reset and account notifications
# Development: Print emails to console
# Production: Use SMTP (configure via environment variables)

if DEBUG:
    # Development - print emails to console for testing
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production - use SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# From email for all messages (used by both development and production)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Language Learning Platform <noreply@languagelearningplatform.org>')

# Password reset token expiration (in seconds) - 20 minutes for security
PASSWORD_RESET_TIMEOUT = 1200  # 20 minutes in seconds

# =============================================================================
# CACHE SETTINGS
# =============================================================================

# Cache configuration for rate limiting and performance
#
# DEVELOPMENT ONLY: Currently using local memory cache
# This configuration is suitable for development and testing but NOT for production.
#
# For production deployment, configure a robust caching backend:
# - Redis: Recommended for high-performance caching and rate limiting
#   * SECURITY: Use password authentication (requirepass in redis.conf)
#   * SECURITY: Bind Redis to localhost or use firewall rules
#   * SECURITY: Use TLS for connections over public networks
#   * SECURITY: Regularly update Redis to patch security vulnerabilities
# - Memcached: Alternative high-performance distributed caching
#   * SECURITY: Bind to localhost or use firewall to restrict access
#   * SECURITY: Use SASL authentication if available
#
# Local memory cache limitations:
# - Not shared across multiple server processes/instances
# - Lost when server restarts
# - Not suitable for load-balanced deployments
#
# To use Redis in production, install django-redis and configure:
# Automatically use Redis in production if REDIS_URL is set, otherwise use local memory
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    # Production: Use Redis for caching (shared across processes)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PASSWORD': os.environ.get('REDIS_PASSWORD'),  # Optional password auth
                'SOCKET_CONNECT_TIMEOUT': 5,  # seconds
                'SOCKET_TIMEOUT': 5,  # seconds
                'RETRY_ON_TIMEOUT': True,
                'MAX_CONNECTIONS': 50,
            }
        }
    }
else:
    # Development: Use local memory cache (not shared across processes)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'OPTIONS': {
                'MAX_ENTRIES': 1000,
            }
        }
    }

    # Warn if using local memory in production
    if not DEBUG:
        import warnings
        warnings.warn(
            'WARNING: Using local memory cache in production! '
            'This cache is not shared across processes and will cause issues with '
            'rate limiting and session management in multi-process deployments. '
            'Set REDIS_URL environment variable to enable Redis caching.',
            RuntimeWarning,
            stacklevel=2
        )

# Session settings
SESSION_COOKIE_AGE = 86400  # Session expires after 1 day (86400 seconds)
SESSION_SAVE_EVERY_REQUEST = True  # Update session on every request to extend expiry

# =============================================================================
# TRUSTED PROXY CONFIGURATION
# =============================================================================

# Control whether to trust X-Forwarded-For header for IP address detection
# SECURITY: Only enable this if you're behind a trusted reverse proxy
#
# Options:
# - 'always': Always trust X-Forwarded-For (suitable for Render, Heroku, etc.)
# - 'debug': Only trust in DEBUG mode (suitable for development with DevEDU)
# - 'never': Never trust, always use REMOTE_ADDR (most secure, but won't work behind proxies)
#
# Default: 'always' for production deployments on cloud platforms
# For self-hosted deployments, consider 'never' or implement IP-based trust validation
TRUST_X_FORWARDED_FOR = os.environ.get('TRUST_X_FORWARDED_FOR', 'always')

# =============================================================================
# SECURITY SETTINGS (Production Only)
# =============================================================================

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Trust the X-Forwarded-Proto header from Render's proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Trust proxy headers in DevEDU environment
if IS_DEVEDU:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allow framing from same origin
