name: AI Code Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AI Code Review
        if: ${{ secrets.OPENAI_API_KEY != '' }}   # run only if the secret exists
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-5            # or gpt-4o-mini if you prefer; keep it simple for now
          PROMPT: |
            Please review the Python/Django code changes and provide feedback on:
              1) Code quality and Django best practices
              2) Potential bugs/issues
              3) Security concerns
              4) Performance considerations
              5) Suggestions for improvement
          top_p: "1"
          temperature: "1"
          max_tokens: "10000"
