name: AI Code Review

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ai-code-review:
    name: AI Code Review with OpenAI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        continue-on-error: true
        
      - name: AI Code Review with OpenAI
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-4
          PROMPT: |
            Please review the following Python/Django code changes and provide feedback on:
            1. Code quality and Django best practices
            2. Potential bugs or issues
            3. Security concerns (especially for web applications)
            4. Performance considerations
            5. Suggestions for improvement
          top_p: 1
          temperature: 1
          max_tokens: 10000
          MAX_PATCH_LENGTH: 10000
        continue-on-error: true
