name: AI Code Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AI Code Review
        if: ${{ secrets.OPENAI_API_KEY }}
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secret.OPENAI_API_KEY }}
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          # Use OPENAI_MODEL secret if set; otherwise fall back to gpt-4o-mini
          MODEL: ${{ secrets.OPENAI_MODEL != '' && secrets.OPENAI_MODEL || 'gpt-4o-mini' }}
          PROMPT: |
            Please review the Python/Django code changes and provide feedback on:
              1) Code quality and Django best practices
              2) Potential bugs/issues
              3) Security concerns
              4) Performance considerations
              5) Suggestions for improvement
          top_p: "1"
          temperature: "1"
          max_tokens: "10000"
